### PR TITLE
Version 1.0

### PR DESCRIPTION
**Pull request by erikaheidi**
Several updates for version 1.0 release.

- Added support for easily creating animated gifs
- Corrected usage of transparency 
- Convenient method for generating text-only images
- Extensive docs

### CODE REVIEW

**Comment by erikaheidi** [comment]
:/ I can't figure out how to add the imagick extension for the Travis builds.

**Comment by douggr** [comment]
@erikaheidi 

in `.travis.yml` add the following lines:

before_script:
  - echo "extension = imagick.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

There you go :)

**Comment by douggr** [comment]
Actually it wont work. My bad, sorry.

```yaml
before_script:
  - pecl install imagick
  - echo "extension = imagick.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
```

**Comment by erikaheidi** [comment]
It's working now, thanks @douggr :D I had to put it in the before_install instead, and add a printf to skip the prompt from pecl.

**Comment by douggr** [comment]
Anytime :)

Cheers

**Comment by erikaheidi** [comment]
ouch. still errored on 5.6

**Comment by erikaheidi** [comment]
Ladies and Gentleman, yes it's passing.

**Pull request merged**
