### PR TITLE
new feature #59 retrieve frames from gif files + remove frames

### PR DESCRIPTION
**Pull request by strayobject**

### CODE REVIEW

**Comment by erikaheidi** [comment]
Hm, it's conflicting. Wondering if a rebase could fix the problem - could you do that, @strayobject ? thank you!

**Comment by strayobject** [comment]
This should be fixed now. I tried merging with a copy of master locally and it has worked. Please let me know if there are any issues still. :)

**Comment by erikaheidi** [comment]
That's awesome, thank you! Merging it now :)

**Comment by erikaheidi** [comment]
I'm making a few changes, just so you know. The method to retrieve the gif frames was added to the AnimatableInterface, and now returns a collection of Imanee objects representing each frame - I did this to enable future implementations of the AnimatableInterface to comply, while also making it possible for the Imanee object to load the frames automatically when opening a gif file (working on that).

**Pull request merged**
